import type { Metadata } from 'next';
import RootStyleRegistry from './emotion';
import { css } from '@emotion/react';
import { globalStyles } from '../../public/styles/GlobalStyle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
}
